server:
  port: 9005

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  application:
    name: zuul-sso
  cloud:
    consul:
      discovery:
        hostname: localhost
        instance-id: ${spring.application.name}:${spring.cloud.consul.discovery.hostname}:${server.port}
      host: localhost
      port: 8500
  redis:
    password: redis

logging:
  level.org.springframework.security: DEBUG

zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  add-proxy-headers: true
  routes:
    rental-route:
      path: /rental/**
      sensitiveHeaders: "*"
      service-id: rental
    iot-route:
      path: /iot/**
      sensitiveHeaders: "*"
      service-id: iot
    mine-route:
      path: /mine/**
      sensitiveHeaders: "*"
      service-id: mine
    uaa-route:
      path: /uaa/**
      sensitiveHeaders: "*"
      service-id: uaa


security:
  oauth2: #为了支持feign配置,可以自定义配置
    client:
      clientId: cloudZuul
      clientSecret: cloudZuulSecret
      accessTokenUri: http://localhost:9003/oauth/token
    resource:
      jwt:
        key-value:
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAimuttOs6TlDDXkTqmjVyEBufUOXH4zajYthUH8aoHCMMHgIKMZ7b0tH/F7PDKOaVtViqbirEU3rMQ80RFMTuCloV24rGjqMZu+QJH8f6iWCHxW269oNaxx7oC5qIo+4mLTdvDRZPam8BHsBRa8W9wakxTnWbZcDkABdgx9bZNUtfBk+Jo1YvIUFpUPnRtKMTAgzdAfb105+3OU3lfA76eWYjGNrRGBHF80/pKo3ob2FE5lJqUt4Z8gVT6g7aT0nFdyr5i/L/Z0sX/yOrrBNBQ6xWF/9HEu8eG5s8iHid0SQr1TEIugDUkA+wv6DT2Kxk/EjvNhhaUHsij4ZZXYaM4wIDAQAB
          -----END PUBLIC KEY-----

