server:
  port: 9005

management:
  endpoints:
    web:
      exposure:
        include: "*"
      cors:
        allowed-origins: "*"
        allowed-methods: "*"
  endpoint:
    health:
      show-details: ALWAYS

spring:
  application:
    name: zuul-sso
  cloud:
    consul:
      discovery:
        hostname: localhost
        instance-id: ${spring.application.name}:${spring.cloud.consul.discovery.hostname}:${server.port}
      host: localhost
      port: 8500

logging:
  level.org.springframework.security: DEBUG

zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  add-proxy-headers: true
  routes:
    rental-route:
      path: /rental/**
      sensitiveHeaders: "*"
      service-id: rental
    iot-route:
      path: /iot/**
      sensitiveHeaders: "*"
      service-id: iot
    mine-route:
      path: /mine/**
      sensitiveHeaders: "*"
      service-id: mine
    uaa-route:
      path: /uaa/**
      sensitiveHeaders: "*"
      service-id: uaa


security:
  oauth2:
    client:
      clientId: cloudZuul
      clientSecret: cloudZuulSecret
      accessTokenUri: http://localhost:9003/oauth/token
      userAuthorizationUri: http://localhost:9003/oauth/authorize
    resource:
      userInfoUri: http://localhost:9003/user
      prefer-token-info: false
      jwt:
        key-uri: http://localhost:9003/oauth/token_key
      token-info-uri: http://localhost:9003/oauth/check_token



